### ISSUE TITLE
The plugin don't work

### ISSUE THREAD

**Issue by andreaschiona** [Perlkonig/grav-plugin-iplocate#6]
I've tryed the plugin but I don't see any data.
- I added the plugin (and enabled it)
- I added the dbip key
- I created the following page:

```
---
title: 'Plugin Demo: ipLocate'
published: true
visible: true
summary:
    enabled: true
    format: short
    size: 128
taxonomy:
    category:
        - ''
    tag:
        - GravDemo
author: aaron
metadata:
    author: aaron
cache_enable: false
twig_first: true
process:
    twig: true
fields:
    - areaCode
    - city
    - continentCode
    - continentName
    - countryCode
    - countryName
    - currencyCode
    - district
    - dmaCode
    - geonameID
    - gmtOffset
    - isp
    - languages
    - latitude
    - longitude
    - metroCode
    - organization
    - regionCode
    - regionName
    - stateProv
    - timezone
    - zipcode
---

| Field | Data |
| ----- | ---- |
{% for field in page.header.fields %}
| {{ field }} | {{ attribute(config.plugins.iplocate, field) }} |
{% endfor %}
```

But all the fields are blank.

Any idea?

Thanks!
Andrea
